language: minimal

jobs:
  include:
    - stage: validate
      script: "docker run --rm -v ${PWD}:/data mivok/markdownlint --rules ~MD013,~MD033,~MD034 $(git ls-files '*.md')"
    - stage: run
      script: "docker run --rm -v ${PWD}/site:/site -v ${PWD}:/docs squidfunk/mkdocs-material build --verbose --clean --strict" # Build a local version of the docs
      before_deploy:
        - "sudo cp ${PWD}/CNAME ${PWD}/site/"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
        local_dir: site
matrix:
  fast_finish: true
